### ISSUE TITLE
Make sure all images have alt-text

### ISSUE THREAD

**Issue by ryaanahmed** [dhmit/computation_hist#345]
All images on our site should have alt-text, to ensure that they are accessible. This is SUPER IMPORTANT. Take ownership of any image you've added personally. (Slash thanks, most images already have alt-text!)

(If you don't know what I'm talking about, please read:
https://www.w3.org/WAI/tutorials/images/
https://www.w3.org/WAI/tutorials/images/#why-is-this-important)

**Comment by Mayowa99** [comment]
I went through the site and it looks like every image has an alt text. For the story teasers, they all say "Teaser for (story name)" but the story name has all the underscores and stuff in it. Idk if that's a problem, but I don't know how else it would be done, since the page was implemented with a for loop.

**Comment by erica02139** [comment]
I agree that all site pages seem to have alt-text and figcaptions--I did notice these don't always show on the test site, but perhaps that's earlier code? Also, the story names display well there!

**Comment by mscuthbert** [comment]
Thanks for doing this @Mayowa99 and @erica02139  -- closing.
